// Data contoh (dev mode) — bentuknya SAMA dengan isi Google Sheets, jadi jalur
// validasi identik. File template CSV di sheets/template/ di-generate dari sini.
// ponytail: Phase 3 memperluas topik/lesson/question; seed tetap dev-only karena
// production diarahkan ke Google Sheets (D-005).

export const SHEET_NAMES = [
  'subjects',
  'curriculum',
  'competencies',
  'topics',
  'lessons',
  'questions',
] as const
export type SheetName = (typeof SHEET_NAMES)[number]

export const seedRows: Record<SheetName, string[][]> = {
  subjects: [
    ['id', 'name', 'emoji', 'color_from', 'color_to', 'description', 'priority', 'status', 'sort_order'],
    ['bahasa-indonesia', 'Bahasa Indonesia', '📖', '#f43f5e', '#be123c', 'Literasi, teks, dan sastra', '1', 'active', '1'],
    ['matematika', 'Matematika', '🔢', '#6366f1', '#4338ca', 'Bilangan, aljabar, geometri, statistika', '1', 'active', '2'],
    ['bahasa-inggris', 'Bahasa Inggris', '🇬🇧', '#0ea5e9', '#0369a1', 'Reading, grammar, vocabulary', '1', 'active', '3'],
    ['ipa', 'IPA', '🔬', '#10b981', '#047857', 'Fisika, kimia, biologi', '1', 'active', '4'],
    ['pendidikan-agama-katolik', 'Pendidikan Agama Katolik', '⛪', '#8b5cf6', '#6d28d9', 'PABP - iman Katolik', '2', 'active', '5'],
    ['ips', 'IPS', '🌍', '#f59e0b', '#b45309', 'Sejarah, geografi, ekonomi', '3', 'coming', '6'],
    ['ppkn', 'PPKn', '🏛️', '#06b6d4', '#0e7490', 'Pancasila & kewarganegaraan', '3', 'coming', '7'],
    ['pjok', 'PJOK', '🏃', '#84cc16', '#4d7c0f', 'Pendidikan jasmani & kesehatan', '3', 'coming', '8'],
    ['prakarya-bk', 'Prakarya & BK', '🛠️', '#14b8a6', '#0f766e', 'Keterampilan & pengembangan diri', '3', 'coming', '9'],
  ],
  curriculum: [
    ['id', 'subject_id', 'title', 'description', 'sort_order'],
    ['cur-mtk-1', 'matematika', 'Bilangan & Aljabar', 'Persamaan, fungsi, dan penerapannya', '1'],
    ['cur-mtk-2', 'matematika', 'Geometri & Statistika', 'Bangun ruang, data, dan peluang', '2'],
    ['cur-bindo-1', 'bahasa-indonesia', 'Teks & Literasi', 'Struktur dan unsur berbagai teks', '1'],
    ['cur-bing-1', 'bahasa-inggris', 'Reading & Grammar', 'Pemahaman teks dan tata bahasa', '1'],
    ['cur-ipa-1', 'ipa', 'IPA Terpadu Kelas 9', 'Fisika, kimia, biologi terpadu', '1'],
    ['cur-pak-1', 'pendidikan-agama-katolik', 'Pribadi Yesus Kristus', 'Injil dan teladan hidup Yesus', '1'],
    ['cur-bing-1', 'bahasa-inggris', 'Reading & Grammar', 'Pemahaman teks dan tata bahasa', '1'],
  ],
  competencies: [
    ['id', 'topic_id', 'code', 'description', 'sort_order'],
    ['comp-pk-2', 'top-persamaan-kuadrat', '9.2.1', 'Menentukan akar-akar persamaan kuadrat', '1'],
    ['comp-pk-2', 'top-persamaan-kuadrat', '9.2.2', 'Menyelesaikan masalah kontekstual persamaan kuadrat', '2'],
    ['comp-st-1', 'top-statistika', '9.6.1', 'Menyajikan data dan menentukan ukuran pemusatan', '1'],
    ['comp-te-1', 'top-teks-eksposisi', '9.1.1', 'Mengidentifikasi struktur teks eksposisi', '1'],
    ['comp-rd-1', 'top-read-1', '9.3.1', 'Menemukan ide utama dan detail teks', '1'],
    ['comp-pk-1', 'top-pak-1', '9.1.1', 'Menjelaskan pribadi Yesus Kristus dalam Injil', '1'],
  ],
  topics: [
    ['id', 'curriculum_id', 'subject_id', 'title', 'description', 'sort_order'],
    ['top-persamaan-kuadrat', 'cur-mtk-1', 'matematika', 'Persamaan Kuadrat', 'Bentuk umum, akar, dan aplikasi', '1'],
    ['top-statistika', 'cur-mtk-2', 'matematika', 'Statistika & Peluang', 'Penyajian data, ukuran pemusatan, peluang', '2'],
    ['top-teks-eksposisi', 'cur-bindo-1', 'bahasa-indonesia', 'Teks Eksposisi', 'Struktur, unsur kebahasaan, dan isi', '1'],
    ['top-listrik-dinamis', 'cur-ipa-1', 'ipa', 'Listrik Dinamis', 'Arus, tegangan, hambatan, rangkaian', '1'],
    ['top-read-1', 'cur-bing-1', 'bahasa-inggris', 'Reading Comprehension', 'Ide utama, detail, dan inferensi teks', '1'],
    ['top-pak-1', 'cur-pak-1', 'pendidikan-agama-katolik', 'Siapakah Yesus?', 'Injil, pribadi, dan teladan Yesus', '1'],
  ],
  lessons: [
    ['id', 'topic_id', 'subject_id', 'title', 'description', 'duration_min', 'type', 'sort_order'],
    ['les-akar-1', 'top-persamaan-kuadrat', 'matematika', 'Akar-akar Persamaan Kuadrat', 'Mengenal bentuk umum dan akar persamaan kuadrat', '15', 'lesson', '1'],
    ['les-akar-2', 'top-persamaan-kuadrat', 'matematika', 'Memfaktorkan & Rumus ABC', 'Cara menentukan akar secara aljabar', '20', 'lesson', '2'],
    ['les-stat-1', 'top-statistika', 'matematika', 'Rata-rata, Median, Modus', 'Ukuran pemusatan data tunggal', '15', 'lesson', '1'],
    ['les-eks-1', 'top-teks-eksposisi', 'bahasa-indonesia', 'Struktur Teks Eksposisi', 'Tesis, argumentasi, penegasan ulang', '10', 'lesson', '1'],
    ['les-eks-2', 'top-teks-eksposisi', 'bahasa-indonesia', 'Unsur Kebahasaan Teks Eksposisi', 'Konjungsi, istilah, dan kalimat persuasif', '10', 'lesson', '2'],
    ['les-listrik-2', 'top-listrik-dinamis', 'ipa', 'Hukum Ohm & Rangkaian', 'Hambatan, arus, rangkaian seri-paralel', '15', 'lesson', '2'],
    ['les-read-1', 'top-read-1', 'bahasa-inggris', 'Main Idea & Detail', 'Menemukan ide utama dan detail pendukung', '10', 'lesson', '1'],
    ['les-read-2', 'top-read-1', 'bahasa-inggris', 'Inference & Vocabulary', 'Menarik kesimpulan dan makna kata', '10', 'lesson', '2'],
    ['les-pak-1', 'top-pak-1', 'pendidikan-agama-katolik', 'Yesus dalam Injil', 'Gambaran Yesus di empat Injil', '10', 'lesson', '1'],
    ['les-pak-2', 'top-pak-1', 'pendidikan-agama-katolik', 'Teladan Hidup Yesus', 'Kasih, pengampunan, dan pelayanan', '10', 'lesson', '2'],
  ],
  questions: [
    ['id', 'lesson_id', 'subject_id', 'type', 'prompt', 'options', 'answer', 'explanation', 'source', 'difficulty'],
    [
      'q-pk-1',
      'les-akar-2',
      'matematika',
      'mcq',
      'Akar-akar persamaan x^2 - 5x + 6 = 0 adalah ...',
      '["2 dan 3","-2 dan -3","1 dan 6","-1 dan -6"]',
      '["0"]',
      'Faktorkan: (x - 2)(x - 3) = 0, sehingga x = 2 atau x = 3.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
    ],
    [
      'q-st-1',
      'les-stat-1',
      'matematika',
      'numeric',
      'Median dari data 3, 5, 7, 9, 11 adalah ...',
      '[]',
      '["7"]',
      'Data sudah terurut; nilai tengah (data ke-3) adalah 7.',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
    ],
    [
      'q-pk-2',
      'les-akar-1',
      'matematika',
      'true_false',
      'Persamaan x^2 = 16 memiliki dua akar berbeda, yaitu 4 dan -4.',
      '[]',
      '["true"]',
      'Benar: x^2 = 16 -> x = 4 atau x = -4, dua akar berbeda.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '1',
    ],
    [
      'q-eks-1',
      'les-eks-1',
      'bahasa-indonesia',
      'mcq',
      'Bagian teks eksposisi yang berisi pendapat penulis disebut ...',
      '["Tesis","Argumentasi","Penegasan ulang","Orientasi"]',
      '["0"]',
      'Tesis adalah pernyataan pendapat penulis di awal teks eksposisi.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
    ],
    [
      'q-eks-2',
      'les-eks-1',
      'bahasa-indonesia',
      'short',
      'Sebutkan satu ciri khas sebuah teks eksposisi.',
      '[]',
      '["pendapat","opini","fakta"]',
      'Teks eksposisi memuat pendapat/opini penulis yang didukung fakta.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
    ],
    [
      'q-st-2',
      'les-stat-1',
      'matematika',
      'mcq',
      'Modus dari data 2, 2, 3, 4, 4, 4, 5 adalah ...',
      '["2","3","4","5"]',
      '["2"]',
      'Nilai yang paling sering muncul: 4 (muncul tiga kali).',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
    ],
  ],
}