// Data contoh (dev mode) — bentuknya SAMA dengan isi Google Sheets, jadi jalur
// validasi identik. File template CSV di sheets/template/ di-generate dari sini.
// ponytail: Phase 3 memperluas topik/lesson/question; seed tetap dev-only karena
// production diarahkan ke Google Sheets (D-005).

export const SHEET_NAMES = [
  'subjects',
  'curriculum',
  'competencies',
  'topics',
  'lessons',
  'questions',
] as const
export type SheetName = (typeof SHEET_NAMES)[number]

export const seedRows: Record<SheetName, string[][]> = {
  subjects: [
    ['id', 'name', 'emoji', 'color_from', 'color_to', 'description', 'priority', 'status', 'sort_order'],
    ['bahasa-indonesia', 'Bahasa Indonesia', '📖', '#f43f5e', '#be123c', 'Literasi, teks, dan sastra', '1', 'active', '1'],
    ['matematika', 'Matematika', '🔢', '#6366f1', '#4338ca', 'Bilangan, aljabar, geometri, statistika', '1', 'active', '2'],
    ['bahasa-inggris', 'Bahasa Inggris', '🇬🇧', '#0ea5e9', '#0369a1', 'Reading, grammar, vocabulary', '1', 'active', '3'],
    ['ipa', 'IPA', '🔬', '#10b981', '#047857', 'Fisika, kimia, biologi', '1', 'active', '4'],
    ['pendidikan-agama-katolik', 'Pendidikan Agama Katolik', '⛪', '#8b5cf6', '#6d28d9', 'PABP - iman Katolik', '2', 'active', '5'],
    ['ips', 'IPS', '🌍', '#f59e0b', '#b45309', 'Sejarah, geografi, ekonomi', '3', 'active', '6'],
    ['ppkn', 'PPKn', '🏛️', '#06b6d4', '#0e7490', 'Pancasila & kewarganegaraan', '3', 'active', '7'],
    ['pjok', 'PJOK', '🏃', '#84cc16', '#4d7c0f', 'Pendidikan jasmani & kesehatan', '3', 'active', '8'],
    ['prakarya-bk', 'Prakarya & BK', '🛠️', '#14b8a6', '#0f766e', 'Keterampilan & pengembangan diri', '3', 'active', '9'],
  ],
  curriculum: [
    ['id', 'subject_id', 'title', 'description', 'sort_order'],
    ['cur-mtk-1', 'matematika', 'Bilangan & Aljabar', 'Persamaan, fungsi, dan penerapannya', '1'],
    ['cur-mtk-2', 'matematika', 'Geometri & Statistika', 'Bangun ruang, data, dan peluang', '2'],
    ['cur-bindo-1', 'bahasa-indonesia', 'Teks & Literasi', 'Struktur dan unsur berbagai teks', '1'],
    ['cur-bing-1', 'bahasa-inggris', 'Reading & Grammar', 'Pemahaman teks dan tata bahasa', '1'],
    ['cur-ipa-1', 'ipa', 'IPA Terpadu Kelas 9', 'Fisika, kimia, biologi terpadu', '1'],
    ['cur-pak-1', 'pendidikan-agama-katolik', 'Pribadi Yesus Kristus', 'Injil dan teladan hidup Yesus', '1'],
    ['cur-ips-1', 'ips', 'Dinamika Keruangan & Interaksi Sosial', 'Perubahan keruangan dan pengaruhnya terhadap kehidupan', '1'],
    ['cur-ppkn-1', 'ppkn', 'Kedaulatan & Konstitusi', 'Dinamika perwujudan Pancasila dan kedaulatan NKRI', '1'],
    ['cur-pjok-1', 'pjok', 'Kebugaran Jasmani & Pola Hidup Sehat', 'Aktivitas kebugaran, pola makan sehat, dan keselamatan', '1'],
    ['cur-prakarya-1', 'prakarya-bk', 'Kerajinan, Teknologi & Perencanaan Karier', 'Prinsip desain, rekayasa sederhana, dan pemahaman bakat', '1'],
  ],
  competencies: [
    ['id', 'topic_id', 'code', 'description', 'sort_order'],
    ['comp-pk-2', 'top-persamaan-kuadrat', '9.2.1', 'Menentukan akar-akar persamaan kuadrat', '1'],
    ['comp-pk-2', 'top-persamaan-kuadrat', '9.2.2', 'Menyelesaikan masalah kontekstual persamaan kuadrat', '2'],
    ['comp-st-1', 'top-statistika', '9.6.1', 'Menyajikan data dan menentukan ukuran pemusatan', '1'],
    ['comp-te-1', 'top-teks-eksposisi', '9.1.1', 'Mengidentifikasi struktur teks eksposisi', '1'],
    ['comp-rd-1', 'top-read-1', '9.3.1', 'Menemukan ide utama dan detail teks', '1'],
    ['comp-pk-1', 'top-pak-1', '9.1.1', 'Menjelaskan pribadi Yesus Kristus dalam Injil', '1'],
    ['comp-ips-1', 'top-ips-globalisasi', '9.3.1', 'Menganalisis dampak globalisasi dalam kehidupan bermasyarakat', '1'],
    ['comp-ppkn-1', 'top-ppkn-pancasila', '9.1.1', 'Mendeskripsikan penerapan Pancasila dari masa ke masa', '1'],
    ['comp-pjok-1', 'top-pjok-kebugaran', '9.4.1', 'Mempraktikkan latihan kebugaran jasmani yang terkait kesehatan', '1'],
    ['comp-prak-1', 'top-prakarya-kerajinan', '9.1.1', 'Memahami desain dan perencanaan karya kerajinan fungsi hias', '1'],
  ],
  topics: [
    ['id', 'curriculum_id', 'subject_id', 'title', 'description', 'sort_order'],
    ['top-persamaan-kuadrat', 'cur-mtk-1', 'matematika', 'Persamaan Kuadrat', 'Bentuk umum, akar, dan aplikasi', '1'],
    ['top-statistika', 'cur-mtk-2', 'matematika', 'Statistika & Peluang', 'Penyajian data, ukuran pemusatan, peluang', '2'],
    ['top-teks-eksposisi', 'cur-bindo-1', 'bahasa-indonesia', 'Teks Eksposisi', 'Struktur, unsur kebahasaan, dan isi', '1'],
    ['top-listrik-dinamis', 'cur-ipa-1', 'ipa', 'Listrik Dinamis', 'Arus, tegangan, hambatan, rangkaian', '1'],
    ['top-read-1', 'cur-bing-1', 'bahasa-inggris', 'Reading Comprehension', 'Ide utama, detail, dan inferensi teks', '1'],
    ['top-pak-1', 'cur-pak-1', 'pendidikan-agama-katolik', 'Siapakah Yesus?', 'Injil, pribadi, dan teladan Yesus', '1'],
    ['top-ips-globalisasi', 'cur-ips-1', 'ips', 'Globalisasi & Perubahan Sosial', 'Dampak positif, negatif, dan sikap menghadapi globalisasi', '1'],
    ['top-ppkn-pancasila', 'cur-ppkn-1', 'ppkn', 'Dinamika Pancasila Sebagai Dasar Negara', 'Penerapan Pancasila era awal kemerdekaan hingga reformasi', '1'],
    ['top-pjok-kebugaran', 'cur-pjok-1', 'pjok', 'Kebugaran Jasmani & Daya Tahan', 'Komponen kekuatan, kelenturan, dan daya tahan jantung', '1'],
    ['top-prakarya-kerajinan', 'cur-prakarya-1', 'prakarya-bk', 'Kerajinan Bahan Keras & Rencana Karier', 'Bahan alam, buatan, serta pemetaan minat masa depan', '1'],
  ],
  lessons: [
    ['id', 'topic_id', 'subject_id', 'title', 'description', 'duration_min', 'type', 'sort_order'],
    ['les-akar-1', 'top-persamaan-kuadrat', 'matematika', 'Akar-akar Persamaan Kuadrat', 'Mengenal bentuk umum dan akar persamaan kuadrat', '15', 'lesson', '1'],
    ['les-akar-2', 'top-persamaan-kuadrat', 'matematika', 'Memfaktorkan & Rumus ABC', 'Cara menentukan akar secara aljabar', '20', 'lesson', '2'],
    ['les-stat-1', 'top-statistika', 'matematika', 'Rata-rata, Median, Modus', 'Ukuran pemusatan data tunggal', '15', 'lesson', '1'],
    ['les-eks-1', 'top-teks-eksposisi', 'bahasa-indonesia', 'Struktur Teks Eksposisi', 'Tesis, argumentasi, penegasan ulang', '10', 'lesson', '1'],
    ['les-eks-2', 'top-teks-eksposisi', 'bahasa-indonesia', 'Unsur Kebahasaan Teks Eksposisi', 'Konjungsi, istilah, dan kalimat persuasif', '10', 'lesson', '2'],
    ['les-listrik-2', 'top-listrik-dinamis', 'ipa', 'Hukum Ohm & Rangkaian', 'Hambatan, arus, rangkaian seri-paralel', '15', 'lesson', '2'],
    ['les-read-1', 'top-read-1', 'bahasa-inggris', 'Main Idea & Detail', 'Menemukan ide utama dan detail pendukung', '10', 'lesson', '1'],
    ['les-read-2', 'top-read-1', 'bahasa-inggris', 'Inference & Vocabulary', 'Menarik kesimpulan dan makna kata', '10', 'lesson', '2'],
    ['les-pak-1', 'top-pak-1', 'pendidikan-agama-katolik', 'Yesus dalam Injil', 'Gambaran Yesus di empat Injil', '10', 'lesson', '1'],
    ['les-pak-2', 'top-pak-1', 'pendidikan-agama-katolik', 'Teladan Hidup Yesus', 'Kasih, pengampunan, dan pelayanan', '10', 'lesson', '2'],
    ['les-ips-1', 'top-ips-globalisasi', 'ips', 'Hakikat Globalisasi & Dampaknya', 'Perkembangan iptek, komunikasi, dan ekonomi dunia', '12', 'lesson', '1'],
    ['les-ppkn-1', 'top-ppkn-pancasila', 'ppkn', 'Penerapan Nilai Pancasila', 'Nilai dasar, instrumental, dan praksis dalam kehidupan', '12', 'lesson', '1'],
    ['les-pjok-1', 'top-pjok-kebugaran', 'pjok', 'Prinsip Latihan Kebugaran', 'Denyut nadi maksimal, daya tahan kardio, dan peregangan', '10', 'lesson', '1'],
    ['les-prakarya-1', 'top-prakarya-kerajinan', 'prakarya-bk', 'Eksplorasi Bahan Keras & Karier', 'Karakteristik kayu, bambu, logam, serta mengenali potensi diri', '12', 'lesson', '1'],
  ],
  questions: [
    ['id', 'lesson_id', 'subject_id', 'type', 'prompt', 'options', 'answer', 'explanation', 'source', 'difficulty', 'hints'],
    [
      'q-pk-1',
      'les-akar-2',
      'matematika',
      'mcq',
      'Akar-akar persamaan kuadrat x² - 5x + 6 = 0 adalah ...',
      '["x = 2 atau x = 3","x = -2 atau x = -3","x = 1 atau x = 6","x = -1 atau x = -6"]',
      '["0"]',
      'Faktorkan menjadi (x - 2)(x - 3) = 0, sehingga pembuat nol adalah x = 2 atau x = 3.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Ubah persamaan ke bentuk faktor: (x - p)(x - q) = 0.","Cari dua bilangan: jika dikali bernilai +6, jika dijumlah bernilai -5."]',
    ],
    [
      'q-pk-2',
      'les-akar-1',
      'matematika',
      'true_false',
      'Persamaan kuadrat x² = 16 memiliki dua akar berlainan, yaitu x = 4 dan x = -4.',
      '[]',
      '["true"]',
      'Benar: kedua nilai jika dikuadratkan menghasilkan 16, yaitu 4² = 16 dan (-4)² = 16.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '1',
      '["Perhatikan operasi akar kuadrat terhadap persamaan kuadrat dapat menghasilkan nilai positif dan negatif."]',
    ],
    [
      'q-pk-match-1',
      'les-akar-1',
      'matematika',
      'matching',
      'Pasangkan nilai diskriminan (D = b² - 4ac) dengan sifat akar persamaan kuadrat yang tepat:',
      '["D > 0 | Dua akar real berlainan","D = 0 | Dua akar real kembar (sama)","D < 0 | Tidak memiliki akar real"]',
      '["D > 0 | Dua akar real berlainan","D = 0 | Dua akar real kembar (sama)","D < 0 | Tidak memiliki akar real"]',
      'Diskriminan menentukan jenis akar: D > 0 memiliki dua akar berbeda, D = 0 memiliki dua akar kembar, dan D < 0 tidak memiliki akar real.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Ingat rumus ABC: x = (-b ± √D) / 2a. Sifat akar ditentukan oleh nilai di dalam tanda akar.","Jika D bernilai negatif, akar kuadrat bilangan negatif tidak menghasilkan bilangan real."]',
    ],
    [
      'q-pk-order-1',
      'les-akar-2',
      'matematika',
      'ordering',
      'Susun langkah-langkah memfaktorkan persamaan kuadrat x² - 5x + 6 = 0 secara berurutan:',
      '["Identifikasi nilai koefisien a = 1, b = -5, dan c = 6","Tentukan pasangan bilangan pemfaktor 6 yang berjumlah -5 (yaitu -2 dan -3)","Tuliskan bentuk perkalian faktor: (x - 2)(x - 3) = 0","Selesaikan nilai x pembuat nol: x = 2 atau x = 3"]',
      '["Identifikasi nilai koefisien a = 1, b = -5, dan c = 6","Tentukan pasangan bilangan pemfaktor 6 yang berjumlah -5 (yaitu -2 dan -3)","Tuliskan bentuk perkalian faktor: (x - 2)(x - 3) = 0","Selesaikan nilai x pembuat nol: x = 2 atau x = 3"]',
      'Urutan yang runtut: periksa koefisien, cari pasangan angka pembuat nol, tulis faktor, dan peroleh nilai x.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Langkah awal adalah menganalisis persamaan dan mencari nilai a, b, c.","Langkah akhir selalu menyelesaikan nilai x yang dicari."]',
    ],
    [
      'q-st-1',
      'les-stat-1',
      'matematika',
      'numeric',
      'Berapa nilai median dari data berikut: 3, 5, 7, 9, 11?',
      '[]',
      '["7"]',
      'Data sudah berurutan dari kecil ke besar dengan jumlah n = 5 (ganjil). Nilai tengahnya adalah data ke-3, yaitu 7.',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
      '["Median adalah nilai yang membagi data terurut menjadi dua bagian sama banyak.","Karena datanya ada 5, ambil angka persis di posisi tengah."]',
    ],
    [
      'q-st-2',
      'les-stat-1',
      'matematika',
      'mcq',
      'Modus dari kumpulan data: 2, 2, 3, 4, 4, 4, 5 adalah ...',
      '["2","3","4","5"]',
      '["2"]',
      'Modus adalah nilai yang paling sering muncul. Angka 4 muncul sebanyak 3 kali (lebih sering daripada angka lain).',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
      '["Modus berkaitan dengan frekuensi kemunculan data terbanyak."]',
    ],
    [
      'q-eks-1',
      'les-eks-1',
      'bahasa-indonesia',
      'mcq',
      'Bagian teks eksposisi yang memuat pengenalan isu, masalah, serta pandangan umum penulis disebut ...',
      '["Tesis","Rangkaian Argumen","Penegasan Ulang","Koda"]',
      '["0"]',
      'Tesis adalah bagian pembuka yang memuat sudut pandang atau teori penulis terhadap topik yang dibahas.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
      '["Pikirkan bagian paling awal dalam struktur teks sebelum bukti-bukti dijabarkan."]',
    ],
    [
      'q-eks-2',
      'les-eks-1',
      'bahasa-indonesia',
      'short',
      'Sebutkan satu ciri khas informasi yang disajikan dalam teks eksposisi.',
      '[]',
      '["fakta","objektif","logis","nyata","ilmiah"]',
      'Teks eksposisi menyajikan gagasan yang didukung oleh fakta dan informasi yang bersifat objektif.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
      '["Teks eksposisi bukan karangan fiksi atau khayalan belaka.","Informasi yang disampaikan harus dapat dibuktikan kebenarannya."]',
    ],
    [
      'q-eks-order-1',
      'les-eks-1',
      'bahasa-indonesia',
      'ordering',
      'Susun struktur penulisan teks eksposisi dari awal hingga akhir:',
      '["Tesis (Pengenalan Isu & Pandangan Penulis)","Rangkaian Argumen (Fakta, Alasan, & Bukti Pendukung)","Penegasan Ulang (Simpulan & Rekomendasi)"]',
      '["Tesis (Pengenalan Isu & Pandangan Penulis)","Rangkaian Argumen (Fakta, Alasan, & Bukti Pendukung)","Penegasan Ulang (Simpulan & Rekomendasi)"]',
      'Struktur baku teks eksposisi adalah Tesis -> Rangkaian Argumen -> Penegasan Ulang.',
      'Adaptasi BSE Bahasa Indonesia SMP Kelas IX, Kemdikbud',
      '1',
      '["Teks eksposisi selalu diawali dengan pengenalan isu (tesis).","Penutup teks biasanya menegaskan kembali argumen yang sudah dipaparkan."]',
    ],
    [
      'q-listrik-match-1',
      'les-listrik-2',
      'ipa',
      'matching',
      'Pasangkan besaran listrik dengan satuan internasional (SI) yang tepat:',
      '["Kuat Arus Listrik | Ampere (A)","Beda Potensial (Tegangan) | Volt (V)","Hambatan Listrik | Ohm (Ω)"]',
      '["Kuat Arus Listrik | Ampere (A)","Beda Potensial (Tegangan) | Volt (V)","Hambatan Listrik | Ohm (Ω)"]',
      'Satuan SI: Kuat Arus adalah Ampere (A), Tegangan adalah Volt (V), dan Hambatan adalah Ohm (Ω).',
      'Adaptasi BSE IPA Terpadu SMP Kelas IX, Kemdikbud',
      '1',
      '["Ingat Hukum Ohm: V = I × R.","I dinyatakan dalam Ampere, V dalam Volt, dan R dalam Ohm."]',
    ],
    [
      'q-ips-1',
      'les-ips-1',
      'ips',
      'mcq',
      'Salah satu dampak positif globalisasi di bidang ekonomi adalah ...',
      '["Meningkatnya pasar internasional bagi produk lokal","Menyempitnya lapangan pekerjaan","Hilangnya identitas budaya lokal","Ketergantungan penuh pada produk impor"]',
      '["0"]',
      'Globalisasi membuka akses perdagangan bebas dan memperluas jangkauan ekspor produk lokal ke kancah mancanegara.',
      'BSE Ilmu Pengetahuan Sosial SMP Kelas IX, Kemdikbud',
      '1',
      '["Pilihlah opsi yang memberikan peluang kemajuan usaha bagi masyarakat."]',
    ],
    [
      'q-ppkn-1',
      'les-ppkn-1',
      'ppkn',
      'mcq',
      'Pancasila memiliki sifat terbuka yang artinya ...',
      '["Mampu menyesuaikan diri dengan perkembangan zaman tanpa mengubah nilai dasarnya","Bebas diubah isinya sesuai keinginan golongan mayoritas","Dapat diganti kapan saja ketika ada ideologi baru","Hanya berlaku pada periode masa kemerdekaan"]',
      '["0"]',
      'Keterbukaan ideologi Pancasila berarti nilai-nilai dasarnya tetap abadi, namun nilai instrumental dan praksisnya dinamis serta terbuka terhadap kemajuan iptek dan zaman.',
      'BSE Pendidikan Pancasila dan Kewarganegaraan SMP Kelas IX, Kemdikbud',
      '1',
      '["Keterbukaan ideologi bukan berarti mengubah asas dasarnya, melainkan adaptif."]',
    ],
    [
      'q-pjok-1',
      'les-pjok-1',
      'pjok',
      'mcq',
      'Kemampuan jantung dan paru-paru untuk menyuplai oksigen ke seluruh tubuh saat beraktivitas fisik dalam waktu lama disebut ...',
      '["Daya tahan kardiorespirasi","Kelentukan otot","Kecepatan reaksi","Kekuatan maksimal"]',
      '["0"]',
      'Daya tahan kardiorespirasi (kardiovaskular) adalah indikator utama kebugaran aerobik yang melibatkan kerja efisien jantung dan paru-paru.',
      'BSE Pendidikan Jasmani, Olahraga, dan Kesehatan SMP Kelas IX, Kemdikbud',
      '1',
      '["Kata kunci ada pada keterlibatan organ jantung (kardio) dan sistem pernapasan (respirasi)."]',
    ],
    [
      'q-prakarya-1',
      'les-prakarya-1',
      'prakarya-bk',
      'mcq',
      'Di bawah ini yang merupakan contoh bahan keras alam yang sering digunakan dalam karya kerajinan adalah ...',
      '["Kayu, bambu, dan rotan","Plastik, kaca, dan kaleng","Fiberglass, lilin, dan gips","Busa, kain perca, dan spons"]',
      '["0"]',
      'Kayu, bambu, dan rotan merupakan bahan keras yang diperoleh langsung dari sumber daya alam nabati tanpa proses kimiawi buatan pabrik.',
      'BSE Prakarya SMP Kelas IX, Kemdikbud',
      '1',
      '["Bahan alam diperoleh langsung dari alam sekitar, bukan hasil olahan sintetis/pabrikan."]',
    ],
  ],
}