// Data contoh (dev mode) — bentuknya SAMA dengan isi Google Sheets, jadi jalur
// validasi identik. File template CSV di sheets/template/ di-generate dari sini.
// Menyediakan bank kurikulum & soal untuk SMP Kelas 9 (Albert) dan SMP Kelas 8 (Jasmine).

export const SHEET_NAMES = [
  'subjects',
  'curriculum',
  'competencies',
  'topics',
  'lessons',
  'questions',
] as const
export type SheetName = (typeof SHEET_NAMES)[number]

export const seedRows: Record<SheetName, string[][]> = {
  subjects: [
    ['id', 'name', 'emoji', 'color_from', 'color_to', 'description', 'priority', 'status', 'sort_order'],
    ['bahasa-indonesia', 'Bahasa Indonesia', '📖', '#f43f5e', '#be123c', 'Literasi, teks, dan sastra', '1', 'active', '1'],
    ['matematika', 'Matematika', '🔢', '#6366f1', '#4338ca', 'Bilangan, aljabar, geometri, statistika', '1', 'active', '2'],
    ['bahasa-inggris', 'Bahasa Inggris', '🇬🇧', '#0ea5e9', '#0369a1', 'Reading, grammar, vocabulary', '1', 'active', '3'],
    ['ipa', 'IPA', '🔬', '#10b981', '#047857', 'Fisika, kimia, biologi', '1', 'active', '4'],
    ['pendidikan-agama-katolik', 'Pendidikan Agama Katolik', '⛪', '#8b5cf6', '#6d28d9', 'PABP - iman Katolik', '2', 'active', '5'],
    ['ips', 'IPS', '🌍', '#f59e0b', '#b45309', 'Sejarah, geografi, ekonomi', '3', 'active', '6'],
    ['ppkn', 'PPKn', '🏛️', '#06b6d4', '#0e7490', 'Pancasila & kewarganegaraan', '3', 'active', '7'],
    ['pjok', 'PJOK', '🏃', '#84cc16', '#4d7c0f', 'Pendidikan jasmani & kesehatan', '3', 'active', '8'],
    ['prakarya-bk', 'Prakarya & BK', '🛠️', '#14b8a6', '#0f766e', 'Keterampilan & pengembangan diri', '3', 'active', '9'],
  ],
  curriculum: [
    ['id', 'subject_id', 'title', 'description', 'sort_order', 'grade'],
    // --- Kelas 9 (Albert) ---
    ['cur-mtk-1', 'matematika', 'Bilangan & Aljabar', 'Persamaan, fungsi, dan penerapannya', '1', '9'],
    ['cur-mtk-2', 'matematika', 'Geometri & Statistika', 'Bangun ruang, data, dan peluang', '2', '9'],
    ['cur-bindo-1', 'bahasa-indonesia', 'Teks & Literasi', 'Struktur dan unsur berbagai teks', '1', '9'],
    ['cur-bing-1', 'bahasa-inggris', 'Reading & Grammar', 'Pemahaman teks dan tata bahasa', '1', '9'],
    ['cur-ipa-1', 'ipa', 'IPA Terpadu Kelas 9', 'Fisika, kimia, biologi terpadu', '1', '9'],
    ['cur-pak-1', 'pendidikan-agama-katolik', 'Pribadi Yesus Kristus', 'Injil dan teladan hidup Yesus', '1', '9'],
    ['cur-ips-1', 'ips', 'Dinamika Keruangan & Interaksi Sosial', 'Perubahan keruangan dan pengaruhnya terhadap kehidupan', '1', '9'],
    ['cur-ppkn-1', 'ppkn', 'Kedaulatan & Konstitusi', 'Dinamika perwujudan Pancasila dan kedaulatan NKRI', '1', '9'],
    ['cur-pjok-1', 'pjok', 'Kebugaran Jasmani & Pola Hidup Sehat', 'Aktivitas kebugaran, pola makan sehat, dan keselamatan', '1', '9'],
    ['cur-prakarya-1', 'prakarya-bk', 'Kerajinan, Teknologi & Perencanaan Karier', 'Prinsip desain, rekayasa sederhana, dan pemahaman bakat', '1', '9'],

    // --- Kelas 8 (Jasmine) ---
    ['cur-mtk-k8-1', 'matematika', 'Aljabar & Pola Bilangan Kelas 8', 'Pola bilangan, relasi, fungsi, dan koordinat Kartesius', '10', '8'],
    ['cur-mtk-k8-2', 'matematika', 'Geometri & Teorema Pythagoras Kelas 8', 'Teorema Pythagoras dan bangun ruang sisi datar', '11', '8'],
    ['cur-ipa-k8-1', 'ipa', 'Gerak, Usaha & Sistem Tubuh Kelas 8', 'Hukum gerak Newton, pesawat sederhana, dan sistem pencernaan', '10', '8'],
    ['cur-bindo-k8-1', 'bahasa-indonesia', 'Informasi & Teks Persuasi Kelas 8', 'Teks berita ADIKSIMBA, slogan, poster, dan iklan komersial', '10', '8'],
    ['cur-bing-k8-1', 'bahasa-inggris', 'Past Experiences & Comparisons Kelas 8', 'Recount text, degree of comparison, and descriptive text', '10', '8'],
    ['cur-pak-k8-1', 'pendidikan-agama-katolik', 'Warta Kerajaan Allah & Sakramen Kelas 8', 'Pribadi Yesus, perumpamaan, dan sakramen Gereja Katolik', '10', '8'],
    ['cur-ips-k8-1', 'ips', 'Keruangan ASEAN & Kehidupan Bangsa Kelas 8', 'Interaksi keruangan negara ASEAN dan pengaruh dinamika sosial', '10', '8'],
    ['cur-ppkn-k8-1', 'ppkn', 'Pancasila & Kesadaran Konstitusi Kelas 8', 'Kedudukan Pancasila dan ketaatan tata perundangan nasional', '10', '8'],
    ['cur-pjok-k8-1', 'pjok', 'Permainan Bola & Kebugaran Remaja Kelas 8', 'Teknik bola basket, kebugaran jasmani, dan pola hidup sehat', '10', '8'],
    ['cur-prakarya-k8-1', 'prakarya-bk', 'Kerajinan Bahan Lunak & Potensi Remaja Kelas 8', 'Karya bahan lunak alam/buatan dan pengenalan minat bakat', '10', '8'],
  ],
  competencies: [
    ['id', 'topic_id', 'code', 'description', 'sort_order', 'grade'],
    // --- Kelas 9 (Albert) ---
    ['comp-pk-2', 'top-persamaan-kuadrat', '9.2.1', 'Menentukan akar-akar persamaan kuadrat', '1', '9'],
    ['comp-pk-2-b', 'top-persamaan-kuadrat', '9.2.2', 'Menyelesaikan masalah kontekstual persamaan kuadrat', '2', '9'],
    ['comp-st-1', 'top-statistika', '9.6.1', 'Menyajikan data dan menentukan ukuran pemusatan', '1', '9'],
    ['comp-te-1', 'top-teks-eksposisi', '9.1.1', 'Mengidentifikasi struktur teks eksposisi', '1', '9'],
    ['comp-rd-1', 'top-read-1', '9.3.1', 'Menemukan ide utama dan detail teks', '1', '9'],
    ['comp-pk-1', 'top-pak-1', '9.1.1', 'Menjelaskan pribadi Yesus Kristus dalam Injil', '1', '9'],
    ['comp-ips-1', 'top-ips-globalisasi', '9.3.1', 'Menganalisis dampak globalisasi dalam kehidupan bermasyarakat', '1', '9'],
    ['comp-ppkn-1', 'top-ppkn-pancasila', '9.1.1', 'Mendeskripsikan penerapan Pancasila dari masa ke masa', '1', '9'],
    ['comp-pjok-1', 'top-pjok-kebugaran', '9.4.1', 'Mempraktikkan latihan kebugaran jasmani yang terkait kesehatan', '1', '9'],
    ['comp-prak-1', 'top-prakarya-kerajinan', '9.1.1', 'Memahami desain dan perencanaan karya kerajinan fungsi hias', '1', '9'],

    // --- Kelas 8 (Jasmine) ---
    ['comp-k8-pola', 'top-k8-pola-bilangan', '8.1.1', 'Menentukan pola barisan bilangan dan konfigurasi objek', '1', '8'],
    ['comp-k8-pyth', 'top-k8-pythagoras', '8.6.1', 'Membuktikan dan menerapkan teorema Pythagoras', '1', '8'],
    ['comp-k8-newton', 'top-k8-gerak-newton', '8.1.1', 'Menganalisis gerak lurus dan pengaruh gaya berdasarkan Hukum Newton', '1', '8'],
    ['comp-k8-cerna', 'top-k8-pencernaan', '8.5.1', 'Menganalisis sistem pencernaan dan zat makanan pada manusia', '1', '8'],
    ['comp-k8-berita', 'top-k8-teks-berita', '8.1.1', 'Mengidentifikasi unsur-unsur teks berita yang didengar dan dibaca', '1', '8'],
    ['comp-k8-recount', 'top-k8-recount-text', '8.4.1', 'Memahami makna teks recount lisan dan tulis terkait pengalaman pribadi', '1', '8'],
    ['comp-k8-pak', 'top-k8-pak-kerajaan', '8.1.1', 'Memahami warta Kerajaan Allah dalam perumpamaan dan tindakan Yesus', '1', '8'],
    ['comp-k8-asean', 'top-k8-asean-geo', '8.1.1', 'Menjelaskan kondisi keruangan dan potensi negara-negara ASEAN', '1', '8'],
    ['comp-k8-ppkn', 'top-k8-ppkn-pancasila', '8.1.1', 'Mendeskripsikan kedudukan dan fungsi Pancasila bagi bangsa Indonesia', '1', '8'],
    ['comp-k8-pjok', 'top-k8-pjok-basket', '8.1.1', 'Mempraktikkan gerak spesifik passing dan dribble bola basket', '1', '8'],
    ['comp-k8-prakarya', 'top-k8-prakarya-lunak', '8.1.1', 'Memahami prinsip perancangan karya kerajinan dari bahan lunak', '1', '8'],
  ],
  topics: [
    ['id', 'curriculum_id', 'subject_id', 'title', 'description', 'sort_order', 'grade'],
    // --- Kelas 9 (Albert) ---
    ['top-persamaan-kuadrat', 'cur-mtk-1', 'matematika', 'Persamaan Kuadrat', 'Bentuk umum, akar, dan aplikasi', '1', '9'],
    ['top-statistika', 'cur-mtk-2', 'matematika', 'Statistika & Peluang', 'Penyajian data, ukuran pemusatan, peluang', '2', '9'],
    ['top-teks-eksposisi', 'cur-bindo-1', 'bahasa-indonesia', 'Teks Eksposisi', 'Struktur, unsur kebahasaan, dan isi', '1', '9'],
    ['top-listrik-dinamis', 'cur-ipa-1', 'ipa', 'Listrik Dinamis', 'Arus, tegangan, hambatan, rangkaian', '1', '9'],
    ['top-read-1', 'cur-bing-1', 'bahasa-inggris', 'Reading Comprehension', 'Ide utama, detail, dan inferensi teks', '1', '9'],
    ['top-pak-1', 'cur-pak-1', 'pendidikan-agama-katolik', 'Siapakah Yesus?', 'Injil, pribadi, dan teladan Yesus', '1', '9'],
    ['top-ips-globalisasi', 'cur-ips-1', 'ips', 'Globalisasi & Perubahan Sosial', 'Dampak positif, negatif, dan sikap menghadapi globalisasi', '1', '9'],
    ['top-ppkn-pancasila', 'cur-ppkn-1', 'ppkn', 'Dinamika Pancasila Sebagai Dasar Negara', 'Penerapan Pancasila era awal kemerdekaan hingga reformasi', '1', '9'],
    ['top-pjok-kebugaran', 'cur-pjok-1', 'pjok', 'Kebugaran Jasmani & Daya Tahan', 'Komponen kekuatan, kelenturan, dan daya tahan jantung', '1', '9'],
    ['top-prakarya-kerajinan', 'cur-prakarya-1', 'prakarya-bk', 'Kerajinan Bahan Keras & Rencana Karier', 'Bahan alam, buatan, serta pemetaan minat masa depan', '1', '9'],

    // --- Kelas 8 (Jasmine) ---
    ['top-k8-pola-bilangan', 'cur-mtk-k8-1', 'matematika', 'Pola Bilangan & Barisan', 'Barisan aritmetika, pola konfigurasi objek, dan rumus suku ke-n', '1', '8'],
    ['top-k8-pythagoras', 'cur-mtk-k8-2', 'matematika', 'Teorema Pythagoras', 'Hubungan sisi segitiga siku-siku dan tripel Pythagoras', '2', '8'],
    ['top-k8-gerak-newton', 'cur-ipa-k8-1', 'ipa', 'Gerak Benda & Hukum Newton', 'Hukum I, II, dan III Newton dalam kehidupan sehari-hari', '1', '8'],
    ['top-k8-pencernaan', 'cur-ipa-k8-1', 'ipa', 'Sistem Pencernaan Manusia', 'Organ pencernaan, enzim pengurai, dan nutrisi makanan', '2', '8'],
    ['top-k8-teks-berita', 'cur-bindo-k8-1', 'bahasa-indonesia', 'Teks Berita (5W+1H)', 'Unsur ADIKSIMBA, kepala berita, tubuh berita, dan fakta faktual', '1', '8'],
    ['top-k8-recount-text', 'cur-bing-k8-1', 'bahasa-inggris', 'Recount Text', 'Personal experiences, past tense, and chronological events', '1', '8'],
    ['top-k8-pak-kerajaan', 'cur-pak-k8-1', 'pendidikan-agama-katolik', 'Kerajaan Allah & Sakramen', 'Perumpamaan Yesus dan sakramen inisiasi umat beriman', '1', '8'],
    ['top-k8-asean-geo', 'cur-ips-k8-1', 'ips', 'Interaksi Keruangan ASEAN', 'Karakteristik geografis, sumber daya alam, dan kerja sama anggota ASEAN', '1', '8'],
    ['top-k8-ppkn-pancasila', 'cur-ppkn-k8-1', 'ppkn', 'Kedudukan & Fungsi Pancasila', 'Pancasila sebagai dasar negara dan pandangan hidup bangsa Indonesia', '1', '8'],
    ['top-k8-pjok-basket', 'cur-pjok-k8-1', 'pjok', 'Bola Basket & Kebugaran Jasmani', 'Teknik passing, dribble, dan latihan daya tahan jasmani Kelas 8', '1', '8'],
    ['top-k8-prakarya-lunak', 'cur-prakarya-k8-1', 'prakarya-bk', 'Kerajinan Bahan Lunak & Minat Bakat', 'Eksplorasi tanah liat, sabun, lilin, serta pemetaan potensi diri', '1', '8'],
  ],
  lessons: [
    ['id', 'topic_id', 'subject_id', 'title', 'description', 'duration_min', 'type', 'sort_order', 'grade'],
    // --- Kelas 9 (Albert) ---
    ['les-akar-1', 'top-persamaan-kuadrat', 'matematika', 'Akar-akar Persamaan Kuadrat', 'Mengenal bentuk umum dan akar persamaan kuadrat', '15', 'lesson', '1', '9'],
    ['les-akar-2', 'top-persamaan-kuadrat', 'matematika', 'Memfaktorkan & Rumus ABC', 'Cara menentukan akar secara aljabar', '20', 'lesson', '2', '9'],
    ['les-stat-1', 'top-statistika', 'matematika', 'Rata-rata, Median, Modus', 'Ukuran pemusatan data tunggal', '15', 'lesson', '1', '9'],
    ['les-eks-1', 'top-teks-eksposisi', 'bahasa-indonesia', 'Struktur Teks Eksposisi', 'Tesis, argumentasi, penegasan ulang', '10', 'lesson', '1', '9'],
    ['les-eks-2', 'top-teks-eksposisi', 'bahasa-indonesia', 'Unsur Kebahasaan Teks Eksposisi', 'Konjungsi, istilah, dan kalimat persuasif', '10', 'lesson', '2', '9'],
    ['les-listrik-2', 'top-listrik-dinamis', 'ipa', 'Hukum Ohm & Rangkaian', 'Hambatan, arus, rangkaian seri-paralel', '15', 'lesson', '2', '9'],
    ['les-read-1', 'top-read-1', 'bahasa-inggris', 'Main Idea & Detail', 'Menemukan ide utama dan detail pendukung', '10', 'lesson', '1', '9'],
    ['les-read-2', 'top-read-1', 'bahasa-inggris', 'Inference & Vocabulary', 'Menarik kesimpulan dan makna kata', '10', 'lesson', '2', '9'],
    ['les-pak-1', 'top-pak-1', 'pendidikan-agama-katolik', 'Yesus dalam Injil', 'Gambaran Yesus di empat Injil', '10', 'lesson', '1', '9'],
    ['les-pak-2', 'top-pak-1', 'pendidikan-agama-katolik', 'Teladan Hidup Yesus', 'Kasih, pengampunan, dan pelayanan', '10', 'lesson', '2', '9'],
    ['les-ips-1', 'top-ips-globalisasi', 'ips', 'Hakikat Globalisasi & Dampaknya', 'Perkembangan iptek, komunikasi, dan ekonomi dunia', '12', 'lesson', '1', '9'],
    ['les-ppkn-1', 'top-ppkn-pancasila', 'ppkn', 'Penerapan Nilai Pancasila', 'Nilai dasar, instrumental, dan praksis dalam kehidupan', '12', 'lesson', '1', '9'],
    ['les-pjok-1', 'top-pjok-kebugaran', 'pjok', 'Prinsip Latihan Kebugaran', 'Denyut nadi maksimal, daya tahan kardio, dan peregangan', '10', 'lesson', '1', '9'],
    ['les-prakarya-1', 'top-prakarya-kerajinan', 'prakarya-bk', 'Eksplorasi Bahan Keras & Karier', 'Karakteristik kayu, bambu, logam, serta mengenali potensi diri', '12', 'lesson', '1', '9'],

    // --- Kelas 8 (Jasmine) ---
    ['les-k8-pola-1', 'top-k8-pola-bilangan', 'matematika', 'Pola Bilangan Aritmetika', 'Suku pertama, beda, dan rumus suku ke-n', '15', 'lesson', '1', '8'],
    ['les-k8-pyth-1', 'top-k8-pythagoras', 'matematika', 'Penerapan Teorema Pythagoras', 'Panjang sisi segitiga siku-siku dan tripel Pythagoras', '15', 'lesson', '1', '8'],
    ['les-k8-newton-1', 'top-k8-gerak-newton', 'ipa', 'Hukum I, II, dan III Newton', 'Inersia, gaya percepatan, serta aksi dan reaksi', '15', 'lesson', '1', '8'],
    ['les-k8-cerna-1', 'top-k8-pencernaan', 'ipa', 'Saluran & Enzim Pencernaan', 'Mulut, lambung, usus halus, dan fungsi enzim pencernaan', '15', 'lesson', '1', '8'],
    ['les-k8-berita-1', 'top-k8-teks-berita', 'bahasa-indonesia', 'Unsur Teks Berita ADIKSIMBA', 'Apa, Di mana, Kapan, Siapa, Mengapa, dan Bagaimana', '12', 'lesson', '1', '8'],
    ['les-k8-recount-1', 'top-k8-recount-text', 'bahasa-inggris', 'Understanding Recount Text', 'Orientation, series of events, and personal reaction', '12', 'lesson', '1', '8'],
    ['les-k8-pak-1', 'top-k8-pak-kerajaan', 'pendidikan-agama-katolik', 'Perumpamaan Kerajaan Allah', 'Makna perumpamaan penabur dan biji sesawi', '10', 'lesson', '1', '8'],
    ['les-k8-asean-1', 'top-k8-asean-geo', 'ips', 'Mengenal Negara-negara ASEAN', 'Letak geografis, iklim tropis, dan batas wilayah ASEAN', '12', 'lesson', '1', '8'],
    ['les-k8-ppkn-1', 'top-k8-ppkn-pancasila', 'ppkn', 'Fungsi Pancasila Sebagai Pandangan Hidup', 'Pedoman tingkah laku dan moral bangsa Indonesia', '12', 'lesson', '1', '8'],
    ['les-k8-pjok-1', 'top-k8-pjok-basket', 'pjok', 'Kombinasi Passing Bola Basket', 'Chest pass, bounce pass, dan overhead pass', '10', 'lesson', '1', '8'],
    ['les-k8-prakarya-1', 'top-k8-prakarya-lunak', 'prakarya-bk', 'Karakteristik Bahan Lunak Alam & Buatan', 'Tanah liat, sabun batangan, plastisin, dan lilin', '10', 'lesson', '1', '8'],
  ],
  questions: [
    ['id', 'lesson_id', 'subject_id', 'type', 'prompt', 'options', 'answer', 'explanation', 'source', 'difficulty', 'hints', 'grade'],
    // --- Kelas 9 (Albert) ---
    [
      'q-pk-1',
      'les-akar-2',
      'matematika',
      'mcq',
      'Akar-akar persamaan kuadrat x² - 5x + 6 = 0 adalah ...',
      '["x = 2 atau x = 3","x = -2 atau x = -3","x = 1 atau x = 6","x = -1 atau x = -6"]',
      '["0"]',
      'Faktorkan menjadi (x - 2)(x - 3) = 0, sehingga pembuat nol adalah x = 2 atau x = 3.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Ubah persamaan ke bentuk faktor: (x - p)(x - q) = 0.","Cari dua bilangan: jika dikali bernilai +6, jika dijumlah bernilai -5."]',
      '9',
    ],
    [
      'q-pk-2',
      'les-akar-1',
      'matematika',
      'true_false',
      'Persamaan kuadrat x² = 16 memiliki dua akar berlainan, yaitu x = 4 dan x = -4.',
      '[]',
      '["true"]',
      'Benar: kedua nilai jika dikuadratkan menghasilkan 16, yaitu 4² = 16 dan (-4)² = 16.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '1',
      '["Perhatikan operasi akar kuadrat terhadap persamaan kuadrat dapat menghasilkan nilai positif dan negatif."]',
      '9',
    ],
    [
      'q-pk-match-1',
      'les-akar-1',
      'matematika',
      'matching',
      'Pasangkan nilai diskriminan (D = b² - 4ac) dengan sifat akar persamaan kuadrat yang tepat:',
      '["D > 0 | Dua akar real berlainan","D = 0 | Dua akar real kembar (sama)","D < 0 | Tidak memiliki akar real"]',
      '["D > 0 | Dua akar real berlainan","D = 0 | Dua akar real kembar (sama)","D < 0 | Tidak memiliki akar real"]',
      'Diskriminan menentukan jenis akar: D > 0 memiliki dua akar berbeda, D = 0 memiliki dua akar kembar, dan D < 0 tidak memiliki akar real.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Ingat rumus ABC: x = (-b ± √D) / 2a. Sifat akar ditentukan oleh nilai di dalam tanda akar.","Jika D bernilai negatif, akar kuadrat bilangan negatif tidak menghasilkan bilangan real."]',
      '9',
    ],
    [
      'q-pk-order-1',
      'les-akar-2',
      'matematika',
      'ordering',
      'Susun langkah-langkah memfaktorkan persamaan kuadrat x² - 5x + 6 = 0 secara berurutan:',
      '["Identifikasi nilai koefisien a = 1, b = -5, dan c = 6","Tentukan pasangan bilangan pemfaktor 6 yang berjumlah -5 (yaitu -2 dan -3)","Tuliskan bentuk perkalian faktor: (x - 2)(x - 3) = 0","Selesaikan nilai x pembuat nol: x = 2 atau x = 3"]',
      '["Identifikasi nilai koefisien a = 1, b = -5, dan c = 6","Tentukan pasangan bilangan pemfaktor 6 yang berjumlah -5 (yaitu -2 dan -3)","Tuliskan bentuk perkalian faktor: (x - 2)(x - 3) = 0","Selesaikan nilai x pembuat nol: x = 2 atau x = 3"]',
      'Urutan yang runtut: periksa koefisien, cari pasangan angka pembuat nol, tulis faktor, dan peroleh nilai x.',
      'Adaptasi BSE Matematika SMP/MTs Kelas IX, Kemdikbud',
      '2',
      '["Langkah awal adalah menganalisis persamaan dan mencari nilai a, b, c.","Langkah akhir selalu menyelesaikan nilai x yang dicari."]',
      '9',
    ],
    [
      'q-st-1',
      'les-stat-1',
      'matematika',
      'numeric',
      'Berapa nilai median dari data berikut: 3, 5, 7, 9, 11?',
      '[]',
      '["7"]',
      'Data sudah berurutan dari kecil ke besar dengan jumlah n = 5 (ganjil). Nilai tengahnya adalah data ke-3, yaitu 7.',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
      '["Median adalah nilai yang membagi data terurut menjadi dua bagian sama banyak.","Karena datanya ada 5, ambil angka persis di posisi tengah."]',
      '9',
    ],
    [
      'q-st-2',
      'les-stat-1',
      'matematika',
      'mcq',
      'Modus dari kumpulan data: 2, 2, 3, 4, 4, 4, 5 adalah ...',
      '["2","3","4","5"]',
      '["2"]',
      'Modus adalah nilai yang paling sering muncul. Angka 4 muncul sebanyak 3 kali (lebih sering daripada angka lain).',
      'Format AKM Numerasi, Pusmenjar Kemdikbud - adaptasi',
      '1',
      '["Modus berkaitan dengan frekuensi kemunculan data terbanyak."]',
      '9',
    ],
    [
      'q-eks-1',
      'les-eks-1',
      'bahasa-indonesia',
      'mcq',
      'Bagian teks eksposisi yang memuat pengenalan isu, masalah, serta pandangan umum penulis disebut ...',
      '["Tesis","Rangkaian Argumen","Penegasan Ulang","Koda"]',
      '["0"]',
      'Tesis adalah bagian pembuka yang memuat sudut pandang atau teori penulis terhadap topik yang dibahas.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
      '["Pikirkan bagian paling awal dalam struktur teks sebelum bukti-bukti dijabarkan."]',
      '9',
    ],
    [
      'q-eks-2',
      'les-eks-1',
      'bahasa-indonesia',
      'short',
      'Sebutkan satu ciri khas informasi yang disajikan dalam teks eksposisi.',
      '[]',
      '["fakta","objektif","logis","nyata","ilmiah"]',
      'Teks eksposisi menyajikan gagasan yang didukung oleh fakta dan informasi yang bersifat objektif.',
      'Format AKM Literasi, Pusmenjar Kemdikbud - adaptasi',
      '2',
      '["Teks eksposisi bukan karangan fiksi atau khayalan belaka.","Informasi yang disampaikan harus dapat dibuktikan kebenarannya."]',
      '9',
    ],
    [
      'q-eks-order-1',
      'les-eks-1',
      'bahasa-indonesia',
      'ordering',
      'Susun struktur penulisan teks eksposisi dari awal hingga akhir:',
      '["Tesis (Pengenalan Isu & Pandangan Penulis)","Rangkaian Argumen (Fakta, Alasan, & Bukti Pendukung)","Penegasan Ulang (Simpulan & Rekomendasi)"]',
      '["Tesis (Pengenalan Isu & Pandangan Penulis)","Rangkaian Argumen (Fakta, Alasan, & Bukti Pendukung)","Penegasan Ulang (Simpulan & Rekomendasi)"]',
      'Struktur baku teks eksposisi adalah Tesis -> Rangkaian Argumen -> Penegasan Ulang.',
      'Adaptasi BSE Bahasa Indonesia SMP Kelas IX, Kemdikbud',
      '1',
      '["Teks eksposisi selalu diawali dengan pengenalan isu (tesis).","Penutup teks biasanya menegaskan kembali argumen yang sudah dipaparkan."]',
      '9',
    ],
    [
      'q-listrik-match-1',
      'les-listrik-2',
      'ipa',
      'matching',
      'Pasangkan besaran listrik dengan satuan internasional (SI) yang tepat:',
      '["Kuat Arus Listrik | Ampere (A)","Beda Potensial (Tegangan) | Volt (V)","Hambatan Listrik | Ohm (Ω)"]',
      '["Kuat Arus Listrik | Ampere (A)","Beda Potensial (Tegangan) | Volt (V)","Hambatan Listrik | Ohm (Ω)"]',
      'Satuan SI: Kuat Arus adalah Ampere (A), Tegangan adalah Volt (V), dan Hambatan adalah Ohm (Ω).',
      'Adaptasi BSE IPA Terpadu SMP Kelas IX, Kemdikbud',
      '1',
      '["Ingat Hukum Ohm: V = I × R.","I dinyatakan dalam Ampere, V dalam Volt, dan R dalam Ohm."]',
      '9',
    ],
    [
      'q-ips-1',
      'les-ips-1',
      'ips',
      'mcq',
      'Salah satu dampak positif globalisasi di bidang ekonomi adalah ...',
      '["Meningkatnya pasar internasional bagi produk lokal","Menyempitnya lapangan pekerjaan","Hilangnya identitas budaya lokal","Ketergantungan penuh pada produk impor"]',
      '["0"]',
      'Globalisasi membuka akses perdagangan bebas dan memperluas jangkauan ekspor produk lokal ke kancah mancanegara.',
      'BSE Ilmu Pengetahuan Sosial SMP Kelas IX, Kemdikbud',
      '1',
      '["Pilihlah opsi yang memberikan peluang kemajuan usaha bagi masyarakat."]',
      '9',
    ],
    [
      'q-ppkn-1',
      'les-ppkn-1',
      'ppkn',
      'mcq',
      'Pancasila memiliki sifat terbuka yang artinya ...',
      '["Mampu menyesuaikan diri dengan perkembangan zaman tanpa mengubah nilai dasarnya","Bebas diubah isinya sesuai keinginan golongan mayoritas","Dapat diganti kapan saja ketika ada ideologi baru","Hanya berlaku pada periode masa kemerdekaan"]',
      '["0"]',
      'Keterbukaan ideologi Pancasila berarti nilai-nilai dasarnya tetap abadi, namun nilai instrumental dan praksisnya dinamis serta terbuka terhadap kemajuan iptek dan zaman.',
      'BSE Pendidikan Pancasila dan Kewarganegaraan SMP Kelas IX, Kemdikbud',
      '1',
      '["Keterbukaan ideologi bukan berarti mengubah asas dasarnya, melainkan adaptif."]',
      '9',
    ],
    [
      'q-pjok-1',
      'les-pjok-1',
      'pjok',
      'mcq',
      'Kemampuan jantung dan paru-paru untuk menyuplai oksigen ke seluruh tubuh saat beraktivitas fisik dalam waktu lama disebut ...',
      '["Daya tahan kardiorespirasi","Kelentukan otot","Kecepatan reaksi","Kekuatan maksimal"]',
      '["0"]',
      'Daya tahan kardiorespirasi (kardiovaskular) adalah indikator utama kebugaran aerobik yang melibatkan kerja efisien jantung dan paru-paru.',
      'BSE Pendidikan Jasmani, Olahraga, dan Kesehatan SMP Kelas IX, Kemdikbud',
      '1',
      '["Kata kunci ada pada keterlibatan organ jantung (kardio) dan sistem pernapasan (respirasi)."]',
      '9',
    ],
    [
      'q-prakarya-1',
      'les-prakarya-1',
      'prakarya-bk',
      'mcq',
      'Di bawah ini yang merupakan contoh bahan keras alam yang sering digunakan dalam karya kerajinan adalah ...',
      '["Kayu, bambu, dan rotan","Plastik, kaca, dan kaleng","Fiberglass, lilin, dan gips","Busa, kain perca, dan spons"]',
      '["0"]',
      'Kayu, bambu, dan rotan merupakan bahan keras yang diperoleh langsung dari sumber daya alam nabati tanpa proses kimiawi buatan pabrik.',
      'BSE Prakarya SMP Kelas IX, Kemdikbud',
      '1',
      '["Bahan alam diperoleh langsung dari alam sekitar, bukan hasil olahan sintetis/pabrikan."]',
      '9',
    ],

    // --- Kelas 8 (Jasmine) ---
    [
      'q-k8-pola-1',
      'les-k8-pola-1',
      'matematika',
      'mcq',
      'Suku ke-6 dari barisan bilangan 2, 5, 8, 11, ... adalah ...',
      '["14","17","20","23"]',
      '["1"]',
      'Barisan aritmetika dengan suku pertama a = 2 dan beda b = 3. Rumus Un = a + (n-1)b. U6 = 2 + (6-1)×3 = 2 + 15 = 17.',
      'Adaptasi BSE Matematika SMP Kelas VIII, Kemdikbud',
      '1',
      '["Perhatikan selisih tetap antar suku berdekatan adalah 3.","Tambahkan beda 3 secara berturut-turut hingga suku ke-6."]',
      '8',
    ],
    [
      'q-k8-pyth-1',
      'les-k8-pyth-1',
      'matematika',
      'mcq',
      'Sebuah segitiga siku-siku memiliki panjang sisi penyiku 6 cm dan 8 cm. Panjang sisi miringnya adalah ...',
      '["10 cm","12 cm","14 cm","16 cm"]',
      '["0"]',
      'Berdasarkan teorema Pythagoras: c² = a² + b² = 6² + 8² = 36 + 64 = 100, sehingga c = √100 = 10 cm.',
      'Adaptasi BSE Matematika SMP Kelas VIII, Kemdikbud',
      '2',
      '["Gunakan rumus kuadrat sisi miring: c = √(a² + b²).","Kuadratkan 6 dan 8, lalu jumlahkan hasilnya."]',
      '8',
    ],
    [
      'q-k8-pyth-2',
      'les-k8-pyth-1',
      'matematika',
      'true_false',
      'Kelompok bilangan 5, 12, dan 13 merupakan tripel Pythagoras yang membentuk segitiga siku-siku.',
      '[]',
      '["true"]',
      'Benar: 5² + 12² = 25 + 144 = 169. Nilai 13² juga sama dengan 169.',
      'Adaptasi BSE Matematika SMP Kelas VIII, Kemdikbud',
      '1',
      '["Periksa apakah kuadrat sisi terpanjang sama dengan jumlah kuadrat dua sisi lainnya."]',
      '8',
    ],
    [
      'q-k8-newton-1',
      'les-k8-newton-1',
      'ipa',
      'mcq',
      'Ketika kendaraan yang melaju tiba-tiba direm mendadak, tubuh kita terdorong ke depan. Hal ini merupakan pembuktian dari ...',
      '["Hukum I Newton (Inersia)","Hukum II Newton","Hukum III Newton","Hukum Pascal"]',
      '["0"]',
      'Hukum I Newton (hukum kelembaman/inersia) menyatakan setiap benda cenderung mempertahankan keadaan diam atau bergeraknya jika tidak ada gaya luar yang bekerja.',
      'BSE IPA Terpadu SMP Kelas VIII, Kemdikbud',
      '1',
      '["Sifat benda mempertahankan keadaannya disebut sifat kelembaman."]',
      '8',
    ],
    [
      'q-k8-cerna-1',
      'les-k8-cerna-1',
      'ipa',
      'mcq',
      'Enzim ptialin (amilase) yang dihasilkan oleh kelenjar ludah di mulut berfungsi untuk mencerna ...',
      '["Amilum menjadi maltosa (gula sederhana)","Protein menjadi asam amino","Lemak menjadi asam lemak","Mineral menjadi vitamin"]',
      '["0"]',
      'Ptialin bekerja di rongga mulut untuk mengubah karbohidrat kompleks (amilum) menjadi gula sederhana seperti maltosa.',
      'BSE IPA Terpadu SMP Kelas VIII, Kemdikbud',
      '1',
      '["Pencernaan kimiawi pertama di mulut bertujuan menguraikan karbohidrat."]',
      '8',
    ],
    [
      'q-k8-berita-1',
      'les-k8-berita-1',
      'bahasa-indonesia',
      'mcq',
      'Unsur berita \'Mengapa\' (Why) dalam struktur teks berita bertujuan menjelaskan ...',
      '["Alasan atau penyebab terjadinya suatu peristiwa","Waktu terjadinya peristiwa","Tokoh atau pihak yang terlibat","Lokasi peristiwa berlangsung"]',
      '["0"]',
      'Unsur \'Mengapa\' memaparkan latar belakang, motif, atau penyebab suatu peristiwa dapat terjadi.',
      'BSE Bahasa Indonesia SMP Kelas VIII, Kemdikbud',
      '1',
      '["Pikirkan kata tanya yang mencari tahu faktor penyebab suatu kejadian."]',
      '8',
    ],
    [
      'q-k8-recount-1',
      'les-k8-recount-1',
      'bahasa-inggris',
      'mcq',
      '"Last holiday, Jasmine and her family ... to the mountains for camping." Bentuk kata kerja masa lampau yang tepat adalah ...',
      '["went","go","gone","goes"]',
      '["0"]',
      'Recount text menceritakan peristiwa masa lampau menggunakan Simple Past Tense. Bentuk lampau dari kata \'go\' adalah \'went\'.',
      'BSE English in Focus SMP Class VIII, Kemdikbud',
      '1',
      '["Perhatikan penanda waktu \'Last holiday\' yang menunjukkan waktu lampau (past)."]',
      '8',
    ],
    [
      'q-k8-pak-1',
      'les-k8-pak-1',
      'pendidikan-agama-katolik',
      'mcq',
      'Dalam ajaran Gereja Katolik, tiga sakramen yang menjadi dasar inisiasi kehidupan kristiani adalah ...',
      '["Baptis, Krisma (Penguatan), dan Ekaristi","Baptis, Pernikahan, dan Imamat","Ekaristi, Tobat, dan Minyak Suci","Krisma, Tobat, dan Tahbisan"]',
      '["0"]',
      'Tiga Sakramen Inisiasi Katolik adalah Sakramen Baptis (kelahiran baru), Penguatan/Krisma (kedewasaan iman), dan Ekaristi (makanan rohani).',
      'PABP Katolik SMP Kelas VIII, Komisi Kateketik KWI',
      '1',
      '["Sakramen inisiasi adalah sakramen dasar yang diterima umat beriman untuk masuk penuh ke dalam Gereja."]',
      '8',
    ],
    [
      'q-k8-ips-1',
      'les-k8-asean-1',
      'ips',
      'mcq',
      'Satu-satunya negara anggota ASEAN yang wilayahnya sama sekali tidak memiliki laut (landlocked country) adalah ...',
      '["Laos","Kamboja","Vietnam","Myanmar"]',
      '["0"]',
      'Laos adalah satu-satunya negara di Asia Tenggara yang seluruh wilayahnya terkurung oleh daratan negara tetangga.',
      'BSE IPS SMP Kelas VIII, Kemdikbud',
      '1',
      '["Negara ini berbatasan dengan Thailand, Vietnam, Kamboja, Myanmar, dan Tiongkok."]',
      '8',
    ],
    [
      'q-k8-ppkn-1',
      'les-k8-ppkn-1',
      'ppkn',
      'mcq',
      'Pancasila berfungsi sebagai pandangan hidup bangsa Indonesia, yang bermakna bahwa Pancasila menjadi ...',
      '["Pedoman dan petunjuk perilaku moral dalam kehidupan bermasyarakat","Hukum yang hanya berlaku bagi warga negara tertentu","Aturan yang kaku dan tidak boleh ditafsirkan","Dokumen sejarah yang hanya disimpan sebagai arsip"]',
      '["0"]',
      'Sebagai pandangan hidup (way of life), nilai-nilai Pancasila menjadi petunjuk arah dan pedoman etika dalam kehidupan bermasyarakat, berbangsa, dan bernegara.',
      'BSE PPKn SMP Kelas VIII, Kemdikbud',
      '1',
      '["Pandangan hidup menjadi lentera bagi perilaku setiap warga negara sehari-hari."]',
      '8',
    ],
    [
      'q-k8-pjok-1',
      'les-k8-pjok-1',
      'pjok',
      'mcq',
      'Operan bola yang dilakukan dengan cara memantulkan bola ke lantai dalam permainan bola basket disebut ...',
      '["Bounce pass","Chest pass","Overhead pass","Side pass"]',
      '["0"]',
      'Bounce pass adalah teknik passing bola dengan memantulkannya ke lantai agar sulit diintersep oleh pemain bertahan lawan.',
      'BSE PJOK SMP Kelas VIII, Kemdikbud',
      '1',
      '["Kata \'bounce\' dalam bahasa Inggris berarti memantul."]',
      '8',
    ],
    [
      'q-k8-prakarya-1',
      'les-k8-prakarya-1',
      'prakarya-bk',
      'mcq',
      'Contoh bahan lunak alam yang banyak digunakan pengrajin untuk pembuatan guci, tembikar, dan keramik adalah ...',
      '["Tanah liat","Lilin lebah buatan","Sabun batangan","Parafin industri"]',
      '["0"]',
      'Tanah liat merupakan bahan lunak alam yang plastis dan mudah dibentuk saat basah serta mengeras setelah dibakar.',
      'BSE Prakarya SMP Kelas VIII, Kemdikbud',
      '1',
      '["Bahan ini diambil langsung dari alam tanah lempung subur."]',
      '8',
    ],
  ],
}